// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.texera.web.workflowresultstate

object WorkflowresultstateProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.texera.web.workflowresultstate.WorkflowJobResultInfo,
      edu.uci.ics.texera.web.workflowresultstate.OperatorResultInfo
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CixlZHUvdWNpL2ljcy90ZXhlcmEvd29ya2Zsb3dyZXN1bHRzdGF0ZS5wcm90bxIWZWR1LnVjaS5pY3MudGV4ZXJhLndlYhoVc
  2NhbGFwYi9zY2FsYXBiLnByb3RvIpQCChVXb3JrZmxvd0pvYlJlc3VsdEluZm8SdwoNb3BlcmF0b3JfaW5mbxgBIAMoCzI/LmVkd
  S51Y2kuaWNzLnRleGVyYS53ZWIuV29ya2Zsb3dKb2JSZXN1bHRJbmZvLk9wZXJhdG9ySW5mb0VudHJ5QhHiPw4SDG9wZXJhdG9yS
  W5mb1IMb3BlcmF0b3JJbmZvGoEBChFPcGVyYXRvckluZm9FbnRyeRIaCgNrZXkYASABKAlCCOI/BRIDa2V5UgNrZXkSTAoFdmFsd
  WUYAiABKAsyKi5lZHUudWNpLmljcy50ZXhlcmEud2ViLk9wZXJhdG9yUmVzdWx0SW5mb0IK4j8HEgV2YWx1ZVIFdmFsdWU6AjgBI
  kYKEk9wZXJhdG9yUmVzdWx0SW5mbxIwCgt0dXBsZV9jb3VudBgBIAEoBUIP4j8MEgp0dXBsZUNvdW50Ugp0dXBsZUNvdW50QgniP
  wZIAFgAeABiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}