# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edu/uci/ics/amber/engine/architecture/sendsemantics/datatransferpolicy2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edu.uci.ics.amber.engine.common import virtualidentity_pb2 as edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_common_dot_virtualidentity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='edu/uci/ics/amber/engine/architecture/sendsemantics/datatransferpolicy2.proto',
  package='edu.uci.ics.amber.engine.architecture.sendsemantics',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nMedu/uci/ics/amber/engine/architecture/sendsemantics/datatransferpolicy2.proto\x12\x33\x65\x64u.uci.ics.amber.engine.architecture.sendsemantics\x1a\x35\x65\x64u/uci/ics/amber/engine/common/virtualidentity.proto\"\x07\n\x05Pause\"\x08\n\x06Resume\"\xb2\x01\n\x11\x44\x61taSendingPolicy\x12@\n\tpolicyTag\x18\x01 \x02(\x0b\x32-.edu.uci.ics.amber.engine.common.LinkIdentity\x12\x11\n\tbatchSize\x18\x02 \x02(\x05\x12H\n\treceivers\x18\x03 \x03(\x0b\x32\x35.edu.uci.ics.amber.engine.common.ActorVirtualIdentity'
  ,
  dependencies=[edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_common_dot_virtualidentity__pb2.DESCRIPTOR,])




_PAUSE = _descriptor.Descriptor(
  name='Pause',
  full_name='edu.uci.ics.amber.engine.architecture.sendsemantics.Pause',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=196,
)


_RESUME = _descriptor.Descriptor(
  name='Resume',
  full_name='edu.uci.ics.amber.engine.architecture.sendsemantics.Resume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=206,
)


_DATASENDINGPOLICY = _descriptor.Descriptor(
  name='DataSendingPolicy',
  full_name='edu.uci.ics.amber.engine.architecture.sendsemantics.DataSendingPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='policyTag', full_name='edu.uci.ics.amber.engine.architecture.sendsemantics.DataSendingPolicy.policyTag', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batchSize', full_name='edu.uci.ics.amber.engine.architecture.sendsemantics.DataSendingPolicy.batchSize', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receivers', full_name='edu.uci.ics.amber.engine.architecture.sendsemantics.DataSendingPolicy.receivers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=387,
)

_DATASENDINGPOLICY.fields_by_name['policyTag'].message_type = edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_common_dot_virtualidentity__pb2._LINKIDENTITY
_DATASENDINGPOLICY.fields_by_name['receivers'].message_type = edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_common_dot_virtualidentity__pb2._ACTORVIRTUALIDENTITY
DESCRIPTOR.message_types_by_name['Pause'] = _PAUSE
DESCRIPTOR.message_types_by_name['Resume'] = _RESUME
DESCRIPTOR.message_types_by_name['DataSendingPolicy'] = _DATASENDINGPOLICY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pause = _reflection.GeneratedProtocolMessageType('Pause', (_message.Message,), {
  'DESCRIPTOR' : _PAUSE,
  '__module__' : 'edu.uci.ics.amber.engine.architecture.sendsemantics.datatransferpolicy2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.architecture.sendsemantics.Pause)
  })
_sym_db.RegisterMessage(Pause)

Resume = _reflection.GeneratedProtocolMessageType('Resume', (_message.Message,), {
  'DESCRIPTOR' : _RESUME,
  '__module__' : 'edu.uci.ics.amber.engine.architecture.sendsemantics.datatransferpolicy2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.architecture.sendsemantics.Resume)
  })
_sym_db.RegisterMessage(Resume)

DataSendingPolicy = _reflection.GeneratedProtocolMessageType('DataSendingPolicy', (_message.Message,), {
  'DESCRIPTOR' : _DATASENDINGPOLICY,
  '__module__' : 'edu.uci.ics.amber.engine.architecture.sendsemantics.datatransferpolicy2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.architecture.sendsemantics.DataSendingPolicy)
  })
_sym_db.RegisterMessage(DataSendingPolicy)


# @@protoc_insertion_point(module_scope)
