// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package edu.uci.ics.amber.engine.common.virtualidentity

/** final case class LinkIdentity (
  *    from: LayerIdentity,
  *    to: LayerIdentity
  * )
  */
@SerialVersionUID(0L)
final case class LinkIdentity(
    from: edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity,
    to: edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[LinkIdentity] {
  @transient
  private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0

  override def serializedSize: _root_.scala.Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {

    {
      val __v = from
      _output__.writeTag(1, 2)
      _output__.writeUInt32NoTag(__v.serializedSize)
      __v.writeTo(_output__)
    };

    {
      val __v = to
      _output__.writeTag(2, 2)
      _output__.writeUInt32NoTag(__v.serializedSize)
      __v.writeTo(_output__)
    };
    unknownFields.writeTo(_output__)
  }

  def withFrom(__v: edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity): LinkIdentity =
    copy(from = __v)

  def withTo(__v: edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity): LinkIdentity =
    copy(to = __v)

  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)

  def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
    (__fieldNumber: @ _root_.scala.unchecked) match {
      case 1 => from
      case 2 => to
    }
  }

  def getField(
      __field: _root_.scalapb.descriptors.FieldDescriptor
  ): _root_.scalapb.descriptors.PValue = {
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match {
      case 1 => from.toPMessage
      case 2 => to.toPMessage
    }
  }

  def toProtoString: _root_.scala.Predef.String =
    _root_.scalapb.TextFormat.printToUnicodeString(this)

  def companion = edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity

  private[this] def __computeSerializedValue(): _root_.scala.Int = {
    var __size = 0

    {
      val __value = from
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
    };

    {
      val __value = to
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
    };
    __size += unknownFields.serializedSize
    __size
  }
  // @@protoc_insertion_point(GeneratedMessage[edu.uci.ics.amber.engine.common.LinkIdentity])
}

object LinkIdentity
    extends scalapb.GeneratedMessageCompanion[
      edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity
    ] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[
    edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity
  ] = this

  implicit def messageReads: _root_.scalapb.descriptors.Reads[
    edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity
  ] =
    _root_.scalapb.descriptors.Reads {
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(
          __fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
          "FieldDescriptor does not match message type."
        )
        edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity(
          from = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(1).get)
            .get
            .as[edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity],
          to = __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(2).get)
            .get
            .as[edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity]
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }

  implicit class LinkIdentityLens[UpperPB](
      _l: _root_.scalapb.lenses.Lens[
        UpperPB,
        edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity
      ]
  ) extends _root_.scalapb.lenses.ObjectLens[
        UpperPB,
        edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity
      ](_l) {
    def from: _root_.scalapb.lenses.Lens[
      UpperPB,
      edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity
    ] = field(_.from)((c_, f_) => c_.copy(from = f_))
    def to: _root_.scalapb.lenses.Lens[
      UpperPB,
      edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity
    ] = field(_.to)((c_, f_) => c_.copy(to = f_))
  }

  final val FROM_FIELD_NUMBER = 1
  final val TO_FIELD_NUMBER = 2
  lazy val nestedMessagesCompanions
      : Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq.empty
  lazy val defaultInstance = edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity(
    from = edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance,
    to = edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance
  )

  def parseFrom(
      `_input__`: _root_.com.google.protobuf.CodedInputStream
  ): edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity = {
    var __requiredFields0: _root_.scala.Long = 0x3L
    var __from: _root_.scala.Option[edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity] =
      _root_.scala.None
    var __to: _root_.scala.Option[edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity] =
      _root_.scala.None
    var `_unknownFields__` : _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __from = _root_.scala.Some(
            __from.fold(
              _root_.scalapb.LiteParser
                .readMessage[edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity](
                  _input__
                )
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
          __requiredFields0 &= 0xfffffffffffffffeL
        case 18 =>
          __to = _root_.scala.Some(
            __to.fold(
              _root_.scalapb.LiteParser
                .readMessage[edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity](
                  _input__
                )
            )(_root_.scalapb.LiteParser.readMessage(_input__, _))
          )
          __requiredFields0 &= 0xfffffffffffffffdL
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    if (__requiredFields0 != 0L) {
      throw new _root_.com.google.protobuf.InvalidProtocolBufferException(
        "Message missing required fields."
      )
    }
    edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity(
      from = __from.getOrElse(
        edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance
      ),
      to = __to.getOrElse(
        edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance
      ),
      unknownFields =
        if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty
        else _unknownFields__.result()
    )
  }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    VirtualidentityProto.javaDescriptor.getMessageTypes().get(6)

  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor =
    VirtualidentityProto.scalaDescriptor.messages(6)

  def messageCompanionForFieldNumber(
      __number: _root_.scala.Int
  ): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @ _root_.scala.unchecked) match {
      case 1 => __out = edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity
      case 2 => __out = edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity
    }
    __out
  }

  def enumCompanionForFieldNumber(
      __fieldNumber: _root_.scala.Int
  ): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)

  def of(
      from: edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity,
      to: edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity
  ): _root_.edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity =
    _root_.edu.uci.ics.amber.engine.common.virtualidentity.LinkIdentity(
      from,
      to
    )
  // @@protoc_insertion_point(GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.LinkIdentity])
}
