// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.texera.web.workflowruntimestate

object WorkflowruntimestateProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.texera.web.workflowruntimestate.BreakpointEvent,
      edu.uci.ics.texera.web.workflowruntimestate.OperatorBreakpoints,
      edu.uci.ics.texera.web.workflowruntimestate.JobBreakpointStore,
      edu.uci.ics.texera.web.workflowruntimestate.PythonOperatorInfo,
      edu.uci.ics.texera.web.workflowruntimestate.JobPythonStore,
      edu.uci.ics.texera.web.workflowruntimestate.OperatorRuntimeStats,
      edu.uci.ics.texera.web.workflowruntimestate.JobStatsStore,
      edu.uci.ics.texera.web.workflowruntimestate.JobStateStore
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ci1lZHUvdWNpL2ljcy90ZXhlcmEvd29ya2Zsb3dydW50aW1lc3RhdGUucHJvdG8SFmVkdS51Y2kuaWNzLnRleGVyYS53ZWIaF
  XNjYWxhcGIvc2NhbGFwYi5wcm90byLTAgoPQnJlYWtwb2ludEV2ZW50Ei0KCmFjdG9yX3BhdGgYASABKAlCDuI/CxIJYWN0b3JQY
  XRoUglhY3RvclBhdGgSWQoFdHVwbGUYAiABKAsyNy5lZHUudWNpLmljcy50ZXhlcmEud2ViLkJyZWFrcG9pbnRFdmVudC5CcmVha
  3BvaW50VHVwbGVCCuI/BxIFdHVwbGVSBXR1cGxlEjwKD2JyZWFrcG9pbnRfaW5mbxgDIAMoCUIT4j8QEg5icmVha3BvaW50SW5mb
  1IOYnJlYWtwb2ludEluZm8aeAoPQnJlYWtwb2ludFR1cGxlEhcKAmlkGAEgASgDQgfiPwQSAmlkUgJpZBInCghpc19pbnB1dBgCI
  AEoCEIM4j8JEgdpc0lucHV0Ugdpc0lucHV0EiMKBmZpZWxkcxgDIAMoCUIL4j8IEgZmaWVsZHNSBmZpZWxkcyKRAQoTT3BlcmF0b
  3JCcmVha3BvaW50cxJ6ChZ1bnJlc29sdmVkX2JyZWFrcG9pbnRzGAEgAygLMicuZWR1LnVjaS5pY3MudGV4ZXJhLndlYi5CcmVha
  3BvaW50RXZlbnRCGuI/FxIVdW5yZXNvbHZlZEJyZWFrcG9pbnRzUhV1bnJlc29sdmVkQnJlYWtwb2ludHMijwIKEkpvYkJyZWFrc
  G9pbnRTdG9yZRJ0Cg1vcGVyYXRvcl9pbmZvGAEgAygLMjwuZWR1LnVjaS5pY3MudGV4ZXJhLndlYi5Kb2JCcmVha3BvaW50U3Rvc
  mUuT3BlcmF0b3JJbmZvRW50cnlCEeI/DhIMb3BlcmF0b3JJbmZvUgxvcGVyYXRvckluZm8aggEKEU9wZXJhdG9ySW5mb0VudHJ5E
  hoKA2tleRgBIAEoCUII4j8FEgNrZXlSA2tleRJNCgV2YWx1ZRgCIAEoCzIrLmVkdS51Y2kuaWNzLnRleGVyYS53ZWIuT3BlcmF0b
  3JCcmVha3BvaW50c0IK4j8HEgV2YWx1ZVIFdmFsdWU6AjgBIlUKElB5dGhvbk9wZXJhdG9ySW5mbxI/ChBjb25zb2xlX21lc3NhZ
  2VzGAEgAygJQhTiPxESD2NvbnNvbGVNZXNzYWdlc1IPY29uc29sZU1lc3NhZ2VzIoYCCg5Kb2JQeXRob25TdG9yZRJwCg1vcGVyY
  XRvcl9pbmZvGAEgAygLMjguZWR1LnVjaS5pY3MudGV4ZXJhLndlYi5Kb2JQeXRob25TdG9yZS5PcGVyYXRvckluZm9FbnRyeUIR4
  j8OEgxvcGVyYXRvckluZm9SDG9wZXJhdG9ySW5mbxqBAQoRT3BlcmF0b3JJbmZvRW50cnkSGgoDa2V5GAEgASgJQgjiPwUSA2tle
  VIDa2V5EkwKBXZhbHVlGAIgASgLMiouZWR1LnVjaS5pY3MudGV4ZXJhLndlYi5QeXRob25PcGVyYXRvckluZm9CCuI/BxIFdmFsd
  WVSBXZhbHVlOgI4ASLQAQoUT3BlcmF0b3JSdW50aW1lU3RhdHMSUQoFc3RhdGUYASABKA4yLy5lZHUudWNpLmljcy50ZXhlcmEud
  2ViLldvcmtmbG93QWdncmVnYXRlZFN0YXRlQgriPwcSBXN0YXRlUgVzdGF0ZRIwCgtpbnB1dF9jb3VudBgCIAEoA0IP4j8MEgppb
  nB1dENvdW50UgppbnB1dENvdW50EjMKDG91dHB1dF9jb3VudBgDIAEoA0IQ4j8NEgtvdXRwdXRDb3VudFILb3V0cHV0Q291bnQih
  gIKDUpvYlN0YXRzU3RvcmUSbwoNb3BlcmF0b3JfaW5mbxgDIAMoCzI3LmVkdS51Y2kuaWNzLnRleGVyYS53ZWIuSm9iU3RhdHNTd
  G9yZS5PcGVyYXRvckluZm9FbnRyeUIR4j8OEgxvcGVyYXRvckluZm9SDG9wZXJhdG9ySW5mbxqDAQoRT3BlcmF0b3JJbmZvRW50c
  nkSGgoDa2V5GAEgASgJQgjiPwUSA2tleVIDa2V5Ek4KBXZhbHVlGAIgASgLMiwuZWR1LnVjaS5pY3MudGV4ZXJhLndlYi5PcGVyY
  XRvclJ1bnRpbWVTdGF0c0IK4j8HEgV2YWx1ZVIFdmFsdWU6AjgBIoQBCg1Kb2JTdGF0ZVN0b3JlElEKBXN0YXRlGAEgASgOMi8uZ
  WR1LnVjaS5pY3MudGV4ZXJhLndlYi5Xb3JrZmxvd0FnZ3JlZ2F0ZWRTdGF0ZUIK4j8HEgVzdGF0ZVIFc3RhdGUSIAoFZXJyb3IYA
  iABKAlCCuI/BxIFZXJyb3JSBWVycm9yKqQBChdXb3JrZmxvd0FnZ3JlZ2F0ZWRTdGF0ZRIRCg1VTklOSVRJQUxJWkVEEAASCQoFU
  kVBRFkQARILCgdSVU5OSU5HEAISCwoHUEFVU0lORxADEgoKBlBBVVNFRBAEEgwKCFJFU1VNSU5HEAUSDgoKUkVDT1ZFUklORxAGE
  g0KCUNPTVBMRVRFRBAHEgsKB0FCT1JURUQQCBILCgdVTktOT1dOEAlCCeI/BkgAWAB4AGIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}