// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.texera.web.workflowruntimestate

object WorkflowruntimestateProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.texera.web.workflowruntimestate.BreakpointEvent,
      edu.uci.ics.texera.web.workflowruntimestate.OperatorRuntimeStats,
      edu.uci.ics.texera.web.workflowruntimestate.OperatorRuntimeInfo,
      edu.uci.ics.texera.web.workflowruntimestate.WorkflowJobRuntimeInfo
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ci1lZHUvdWNpL2ljcy90ZXhlcmEvd29ya2Zsb3dydW50aW1lc3RhdGUucHJvdG8SFmVkdS51Y2kuaWNzLnRleGVyYS53ZWIaF
  XNjYWxhcGIvc2NhbGFwYi5wcm90byLTAgoPQnJlYWtwb2ludEV2ZW50Ei0KCmFjdG9yX3BhdGgYASABKAlCDuI/CxIJYWN0b3JQY
  XRoUglhY3RvclBhdGgSWQoFdHVwbGUYAiABKAsyNy5lZHUudWNpLmljcy50ZXhlcmEud2ViLkJyZWFrcG9pbnRFdmVudC5CcmVha
  3BvaW50VHVwbGVCCuI/BxIFdHVwbGVSBXR1cGxlEjwKD2JyZWFrcG9pbnRfaW5mbxgDIAMoCUIT4j8QEg5icmVha3BvaW50SW5mb
  1IOYnJlYWtwb2ludEluZm8aeAoPQnJlYWtwb2ludFR1cGxlEhcKAmlkGAEgASgDQgfiPwQSAmlkUgJpZBInCghpc19pbnB1dBgCI
  AEoCEIM4j8JEgdpc0lucHV0Ugdpc0lucHV0EiMKBmZpZWxkcxgDIAMoCUIL4j8IEgZmaWVsZHNSBmZpZWxkcyLQAQoUT3BlcmF0b
  3JSdW50aW1lU3RhdHMSUQoFc3RhdGUYASABKA4yLy5lZHUudWNpLmljcy50ZXhlcmEud2ViLldvcmtmbG93QWdncmVnYXRlZFN0Y
  XRlQgriPwcSBXN0YXRlUgVzdGF0ZRIwCgtpbnB1dF9jb3VudBgCIAEoA0IP4j8MEgppbnB1dENvdW50UgppbnB1dENvdW50EjMKD
  G91dHB1dF9jb3VudBgDIAEoA0IQ4j8NEgtvdXRwdXRDb3VudFILb3V0cHV0Q291bnQitQIKE09wZXJhdG9yUnVudGltZUluZm8ST
  goFc3RhdHMYASABKAsyLC5lZHUudWNpLmljcy50ZXhlcmEud2ViLk9wZXJhdG9yUnVudGltZVN0YXRzQgriPwcSBXN0YXRzUgVzd
  GF0cxJ6ChZ1bnJlc29sdmVkX2JyZWFrcG9pbnRzGAIgAygLMicuZWR1LnVjaS5pY3MudGV4ZXJhLndlYi5CcmVha3BvaW50RXZlb
  nRCGuI/FxIVdW5yZXNvbHZlZEJyZWFrcG9pbnRzUhV1bnJlc29sdmVkQnJlYWtwb2ludHMSUgoXcHl0aG9uX2NvbnNvbGVfbWVzc
  2FnZXMYAyADKAlCGuI/FxIVcHl0aG9uQ29uc29sZU1lc3NhZ2VzUhVweXRob25Db25zb2xlTWVzc2FnZXMijAMKFldvcmtmbG93S
  m9iUnVudGltZUluZm8SUQoFc3RhdGUYASABKA4yLy5lZHUudWNpLmljcy50ZXhlcmEud2ViLldvcmtmbG93QWdncmVnYXRlZFN0Y
  XRlQgriPwcSBXN0YXRlUgVzdGF0ZRIgCgVlcnJvchgCIAEoCUIK4j8HEgVlcnJvclIFZXJyb3ISeAoNb3BlcmF0b3JfaW5mbxgDI
  AMoCzJALmVkdS51Y2kuaWNzLnRleGVyYS53ZWIuV29ya2Zsb3dKb2JSdW50aW1lSW5mby5PcGVyYXRvckluZm9FbnRyeUIR4j8OE
  gxvcGVyYXRvckluZm9SDG9wZXJhdG9ySW5mbxqCAQoRT3BlcmF0b3JJbmZvRW50cnkSGgoDa2V5GAEgASgJQgjiPwUSA2tleVIDa
  2V5Ek0KBXZhbHVlGAIgASgLMisuZWR1LnVjaS5pY3MudGV4ZXJhLndlYi5PcGVyYXRvclJ1bnRpbWVJbmZvQgriPwcSBXZhbHVlU
  gV2YWx1ZToCOAEqlwEKF1dvcmtmbG93QWdncmVnYXRlZFN0YXRlEhEKDVVOSU5JVElBTElaRUQQABIJCgVSRUFEWRABEgsKB1JVT
  k5JTkcQAhILCgdQQVVTSU5HEAMSCgoGUEFVU0VEEAQSDAoIUkVTVU1JTkcQBRIOCgpSRUNPVkVSSU5HEAYSDQoJQ09NUExFVEVEE
  AcSCwoHQUJPUlRFRBAIQgniPwZIAFgAeABiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}