# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edu/uci/ics/amber/engine/common/ambermessage2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from edu.uci.ics.amber.engine.common import virtualidentity_pb2 as edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_common_dot_virtualidentity__pb2
from edu.uci.ics.amber.engine.architecture.worker import promisehandler2_pb2 as edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_architecture_dot_worker_dot_promisehandler2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='edu/uci/ics/amber/engine/common/ambermessage2.proto',
  package='edu.uci.ics.amber.engine.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3edu/uci/ics/amber/engine/common/ambermessage2.proto\x12\x1f\x65\x64u.uci.ics.amber.engine.common\x1a\x19google/protobuf/any.proto\x1a\x35\x65\x64u/uci/ics/amber/engine/common/virtualidentity.proto\x1a\x42\x65\x64u/uci/ics/amber/engine/architecture/worker/promisehandler2.proto\"\r\n\x0b\x44\x61taPayload\"u\n\x11\x43ontrolInvocation\x12\x11\n\tcommandID\x18\x01 \x01(\x03\x12M\n\x07\x63ommand\x18\x02 \x01(\x0b\x32<.edu.uci.ics.amber.engine.architecture.worker.ControlCommand\"q\n\x0e\x43ontrolPayload\x12O\n\x11\x63ontrolInvocation\x18\x01 \x01(\x0b\x32\x32.edu.uci.ics.amber.engine.common.ControlInvocationH\x00\x42\x0e\n\x0csealed_value\"U\n\rReturnPayload\x12\x19\n\x11originalCommandID\x18\x01 \x01(\x03\x12)\n\x0breturnValue\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\xb1\x01\n\x13WorkflowDataMessage\x12\x43\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x35.edu.uci.ics.amber.engine.common.ActorVirtualIdentity\x12\x16\n\x0esequenceNumber\x18\x02 \x01(\x03\x12=\n\x07payload\x18\x03 \x01(\x0b\x32,.edu.uci.ics.amber.engine.common.DataPayload\"\xb7\x01\n\x16WorkflowControlMessage\x12\x43\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x35.edu.uci.ics.amber.engine.common.ActorVirtualIdentity\x12\x16\n\x0esequenceNumber\x18\x02 \x01(\x03\x12@\n\x07payload\x18\x03 \x01(\x0b\x32/.edu.uci.ics.amber.engine.common.ControlPayload\"\xd1\x01\n\x0fWorkflowMessage\x12S\n\x13workflowDataMessage\x18\x01 \x01(\x0b\x32\x34.edu.uci.ics.amber.engine.common.WorkflowDataMessageH\x00\x12Y\n\x16workflowControlMessage\x18\x02 \x01(\x0b\x32\x37.edu.uci.ics.amber.engine.common.WorkflowControlMessageH\x00\x42\x0e\n\x0csealed_valueb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_common_dot_virtualidentity__pb2.DESCRIPTOR,edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_architecture_dot_worker_dot_promisehandler2__pb2.DESCRIPTOR,])




_DATAPAYLOAD = _descriptor.Descriptor(
  name='DataPayload',
  full_name='edu.uci.ics.amber.engine.common.DataPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=251,
)


_CONTROLINVOCATION = _descriptor.Descriptor(
  name='ControlInvocation',
  full_name='edu.uci.ics.amber.engine.common.ControlInvocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandID', full_name='edu.uci.ics.amber.engine.common.ControlInvocation.commandID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='edu.uci.ics.amber.engine.common.ControlInvocation.command', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=370,
)


_CONTROLPAYLOAD = _descriptor.Descriptor(
  name='ControlPayload',
  full_name='edu.uci.ics.amber.engine.common.ControlPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='controlInvocation', full_name='edu.uci.ics.amber.engine.common.ControlPayload.controlInvocation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sealed_value', full_name='edu.uci.ics.amber.engine.common.ControlPayload.sealed_value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=372,
  serialized_end=485,
)


_RETURNPAYLOAD = _descriptor.Descriptor(
  name='ReturnPayload',
  full_name='edu.uci.ics.amber.engine.common.ReturnPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='originalCommandID', full_name='edu.uci.ics.amber.engine.common.ReturnPayload.originalCommandID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='returnValue', full_name='edu.uci.ics.amber.engine.common.ReturnPayload.returnValue', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=572,
)


_WORKFLOWDATAMESSAGE = _descriptor.Descriptor(
  name='WorkflowDataMessage',
  full_name='edu.uci.ics.amber.engine.common.WorkflowDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='edu.uci.ics.amber.engine.common.WorkflowDataMessage.from', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequenceNumber', full_name='edu.uci.ics.amber.engine.common.WorkflowDataMessage.sequenceNumber', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='edu.uci.ics.amber.engine.common.WorkflowDataMessage.payload', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=752,
)


_WORKFLOWCONTROLMESSAGE = _descriptor.Descriptor(
  name='WorkflowControlMessage',
  full_name='edu.uci.ics.amber.engine.common.WorkflowControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='edu.uci.ics.amber.engine.common.WorkflowControlMessage.from', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequenceNumber', full_name='edu.uci.ics.amber.engine.common.WorkflowControlMessage.sequenceNumber', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='edu.uci.ics.amber.engine.common.WorkflowControlMessage.payload', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=755,
  serialized_end=938,
)


_WORKFLOWMESSAGE = _descriptor.Descriptor(
  name='WorkflowMessage',
  full_name='edu.uci.ics.amber.engine.common.WorkflowMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflowDataMessage', full_name='edu.uci.ics.amber.engine.common.WorkflowMessage.workflowDataMessage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workflowControlMessage', full_name='edu.uci.ics.amber.engine.common.WorkflowMessage.workflowControlMessage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sealed_value', full_name='edu.uci.ics.amber.engine.common.WorkflowMessage.sealed_value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=941,
  serialized_end=1150,
)

_CONTROLINVOCATION.fields_by_name['command'].message_type = edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_architecture_dot_worker_dot_promisehandler2__pb2._CONTROLCOMMAND
_CONTROLPAYLOAD.fields_by_name['controlInvocation'].message_type = _CONTROLINVOCATION
_CONTROLPAYLOAD.oneofs_by_name['sealed_value'].fields.append(
  _CONTROLPAYLOAD.fields_by_name['controlInvocation'])
_CONTROLPAYLOAD.fields_by_name['controlInvocation'].containing_oneof = _CONTROLPAYLOAD.oneofs_by_name['sealed_value']
_RETURNPAYLOAD.fields_by_name['returnValue'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_WORKFLOWDATAMESSAGE.fields_by_name['from'].message_type = edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_common_dot_virtualidentity__pb2._ACTORVIRTUALIDENTITY
_WORKFLOWDATAMESSAGE.fields_by_name['payload'].message_type = _DATAPAYLOAD
_WORKFLOWCONTROLMESSAGE.fields_by_name['from'].message_type = edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_common_dot_virtualidentity__pb2._ACTORVIRTUALIDENTITY
_WORKFLOWCONTROLMESSAGE.fields_by_name['payload'].message_type = _CONTROLPAYLOAD
_WORKFLOWMESSAGE.fields_by_name['workflowDataMessage'].message_type = _WORKFLOWDATAMESSAGE
_WORKFLOWMESSAGE.fields_by_name['workflowControlMessage'].message_type = _WORKFLOWCONTROLMESSAGE
_WORKFLOWMESSAGE.oneofs_by_name['sealed_value'].fields.append(
  _WORKFLOWMESSAGE.fields_by_name['workflowDataMessage'])
_WORKFLOWMESSAGE.fields_by_name['workflowDataMessage'].containing_oneof = _WORKFLOWMESSAGE.oneofs_by_name['sealed_value']
_WORKFLOWMESSAGE.oneofs_by_name['sealed_value'].fields.append(
  _WORKFLOWMESSAGE.fields_by_name['workflowControlMessage'])
_WORKFLOWMESSAGE.fields_by_name['workflowControlMessage'].containing_oneof = _WORKFLOWMESSAGE.oneofs_by_name['sealed_value']
DESCRIPTOR.message_types_by_name['DataPayload'] = _DATAPAYLOAD
DESCRIPTOR.message_types_by_name['ControlInvocation'] = _CONTROLINVOCATION
DESCRIPTOR.message_types_by_name['ControlPayload'] = _CONTROLPAYLOAD
DESCRIPTOR.message_types_by_name['ReturnPayload'] = _RETURNPAYLOAD
DESCRIPTOR.message_types_by_name['WorkflowDataMessage'] = _WORKFLOWDATAMESSAGE
DESCRIPTOR.message_types_by_name['WorkflowControlMessage'] = _WORKFLOWCONTROLMESSAGE
DESCRIPTOR.message_types_by_name['WorkflowMessage'] = _WORKFLOWMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPayload = _reflection.GeneratedProtocolMessageType('DataPayload', (_message.Message,), {
  'DESCRIPTOR' : _DATAPAYLOAD,
  '__module__' : 'edu.uci.ics.amber.engine.common.ambermessage2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.common.DataPayload)
  })
_sym_db.RegisterMessage(DataPayload)

ControlInvocation = _reflection.GeneratedProtocolMessageType('ControlInvocation', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLINVOCATION,
  '__module__' : 'edu.uci.ics.amber.engine.common.ambermessage2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.common.ControlInvocation)
  })
_sym_db.RegisterMessage(ControlInvocation)

ControlPayload = _reflection.GeneratedProtocolMessageType('ControlPayload', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLPAYLOAD,
  '__module__' : 'edu.uci.ics.amber.engine.common.ambermessage2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.common.ControlPayload)
  })
_sym_db.RegisterMessage(ControlPayload)

ReturnPayload = _reflection.GeneratedProtocolMessageType('ReturnPayload', (_message.Message,), {
  'DESCRIPTOR' : _RETURNPAYLOAD,
  '__module__' : 'edu.uci.ics.amber.engine.common.ambermessage2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.common.ReturnPayload)
  })
_sym_db.RegisterMessage(ReturnPayload)

WorkflowDataMessage = _reflection.GeneratedProtocolMessageType('WorkflowDataMessage', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWDATAMESSAGE,
  '__module__' : 'edu.uci.ics.amber.engine.common.ambermessage2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.common.WorkflowDataMessage)
  })
_sym_db.RegisterMessage(WorkflowDataMessage)

WorkflowControlMessage = _reflection.GeneratedProtocolMessageType('WorkflowControlMessage', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWCONTROLMESSAGE,
  '__module__' : 'edu.uci.ics.amber.engine.common.ambermessage2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.common.WorkflowControlMessage)
  })
_sym_db.RegisterMessage(WorkflowControlMessage)

WorkflowMessage = _reflection.GeneratedProtocolMessageType('WorkflowMessage', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWMESSAGE,
  '__module__' : 'edu.uci.ics.amber.engine.common.ambermessage2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.common.WorkflowMessage)
  })
_sym_db.RegisterMessage(WorkflowMessage)


# @@protoc_insertion_point(module_scope)
