# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: edu/uci/ics/amber/engine/architecture/worker/promisehandler2.proto
# plugin: python-betterproto
import betterproto
from dataclasses import dataclass

from .edu.uci.ics.amber.engine.architecture import sendsemantics


@dataclass
class Pause(betterproto.Message):
    pass


@dataclass
class Resume(betterproto.Message):
    pass


@dataclass
class StartWorker(betterproto.Message):
    pass


@dataclass
class AddOutputPolicy(betterproto.Message):
    policy: sendsemantics.DataSendingPolicy = betterproto.message_field(1)


@dataclass
class ControlCommand(betterproto.Message):
    pause: "Pause" = betterproto.message_field(1, group="sealed_value")
    resume: "Resume" = betterproto.message_field(2, group="sealed_value")
    add_output_policy: "AddOutputPolicy" = betterproto.message_field(
        3, group="sealed_value"
    )
