# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: edu/uci/ics/amber/engine/architecture/worker/promisehandler2.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


@dataclass(eq=False, repr=False)
class QueryStatistics(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class StartWorker(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WorkerStatistics(betterproto.Message):
    worker_state: "__common__.WorkerState" = betterproto.message_field(1)
    input_row_count: int = betterproto.int64_field(2)
    output_row_count: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class UpdateInputLinking(betterproto.Message):
    identifier: "__common__.ActorVirtualIdentity" = betterproto.message_field(1)
    input_link: "__common__.LinkIdentity" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class AddOutputPolicy(betterproto.Message):
    policy: "_sendsemantics__.DataSendingPolicy" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class WorkerExecutionCompleted(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ControlCommand(betterproto.Message):
    add_output_policy: "AddOutputPolicy" = betterproto.message_field(
        3, group="sealed_value"
    )
    start_worker: "StartWorker" = betterproto.message_field(4, group="sealed_value")
    update_input_linking: "UpdateInputLinking" = betterproto.message_field(
        5, group="sealed_value"
    )
    query_statistics: "QueryStatistics" = betterproto.message_field(
        6, group="sealed_value"
    )
    worker_statistics: "WorkerStatistics" = betterproto.message_field(
        7, group="sealed_value"
    )
    worker_execution_completed: "WorkerExecutionCompleted" = betterproto.message_field(
        101, group="sealed_value"
    )


from .. import sendsemantics as _sendsemantics__
from ... import common as __common__
