# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edu/uci/ics/amber/engine/architecture/worker/promisehandler2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edu.uci.ics.amber.engine.architecture.sendsemantics import datatransferpolicy2_pb2 as edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_architecture_dot_sendsemantics_dot_datatransferpolicy2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='edu/uci/ics/amber/engine/architecture/worker/promisehandler2.proto',
  package='edu.uci.ics.amber.engine.architecture.worker',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBedu/uci/ics/amber/engine/architecture/worker/promisehandler2.proto\x12,edu.uci.ics.amber.engine.architecture.worker\x1aMedu/uci/ics/amber/engine/architecture/sendsemantics/datatransferpolicy2.proto\"\x07\n\x05Pause\"\x08\n\x06Resume\"i\n\x0f\x41\x64\x64OutputPolicy\x12V\n\x06policy\x18\x01 \x02(\x0b\x32\x46.edu.uci.ics.amber.engine.architecture.sendsemantics.DataSendingPolicy\"\x88\x02\n\x0e\x43ontrolCommand\x12\x44\n\x05pause\x18\x01 \x01(\x0b\x32\x33.edu.uci.ics.amber.engine.architecture.worker.PauseH\x00\x12\x46\n\x06resume\x18\x02 \x01(\x0b\x32\x34.edu.uci.ics.amber.engine.architecture.worker.ResumeH\x00\x12X\n\x0f\x61\x64\x64OutputPolicy\x18\x03 \x01(\x0b\x32=.edu.uci.ics.amber.engine.architecture.worker.AddOutputPolicyH\x00\x42\x0e\n\x0csealed_value'
  ,
  dependencies=[edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_architecture_dot_sendsemantics_dot_datatransferpolicy2__pb2.DESCRIPTOR,])




_PAUSE = _descriptor.Descriptor(
  name='Pause',
  full_name='edu.uci.ics.amber.engine.architecture.worker.Pause',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=202,
)


_RESUME = _descriptor.Descriptor(
  name='Resume',
  full_name='edu.uci.ics.amber.engine.architecture.worker.Resume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=212,
)


_ADDOUTPUTPOLICY = _descriptor.Descriptor(
  name='AddOutputPolicy',
  full_name='edu.uci.ics.amber.engine.architecture.worker.AddOutputPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='policy', full_name='edu.uci.ics.amber.engine.architecture.worker.AddOutputPolicy.policy', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=319,
)


_CONTROLCOMMAND = _descriptor.Descriptor(
  name='ControlCommand',
  full_name='edu.uci.ics.amber.engine.architecture.worker.ControlCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pause', full_name='edu.uci.ics.amber.engine.architecture.worker.ControlCommand.pause', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resume', full_name='edu.uci.ics.amber.engine.architecture.worker.ControlCommand.resume', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addOutputPolicy', full_name='edu.uci.ics.amber.engine.architecture.worker.ControlCommand.addOutputPolicy', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sealed_value', full_name='edu.uci.ics.amber.engine.architecture.worker.ControlCommand.sealed_value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=322,
  serialized_end=586,
)

_ADDOUTPUTPOLICY.fields_by_name['policy'].message_type = edu_dot_uci_dot_ics_dot_amber_dot_engine_dot_architecture_dot_sendsemantics_dot_datatransferpolicy2__pb2._DATASENDINGPOLICY
_CONTROLCOMMAND.fields_by_name['pause'].message_type = _PAUSE
_CONTROLCOMMAND.fields_by_name['resume'].message_type = _RESUME
_CONTROLCOMMAND.fields_by_name['addOutputPolicy'].message_type = _ADDOUTPUTPOLICY
_CONTROLCOMMAND.oneofs_by_name['sealed_value'].fields.append(
  _CONTROLCOMMAND.fields_by_name['pause'])
_CONTROLCOMMAND.fields_by_name['pause'].containing_oneof = _CONTROLCOMMAND.oneofs_by_name['sealed_value']
_CONTROLCOMMAND.oneofs_by_name['sealed_value'].fields.append(
  _CONTROLCOMMAND.fields_by_name['resume'])
_CONTROLCOMMAND.fields_by_name['resume'].containing_oneof = _CONTROLCOMMAND.oneofs_by_name['sealed_value']
_CONTROLCOMMAND.oneofs_by_name['sealed_value'].fields.append(
  _CONTROLCOMMAND.fields_by_name['addOutputPolicy'])
_CONTROLCOMMAND.fields_by_name['addOutputPolicy'].containing_oneof = _CONTROLCOMMAND.oneofs_by_name['sealed_value']
DESCRIPTOR.message_types_by_name['Pause'] = _PAUSE
DESCRIPTOR.message_types_by_name['Resume'] = _RESUME
DESCRIPTOR.message_types_by_name['AddOutputPolicy'] = _ADDOUTPUTPOLICY
DESCRIPTOR.message_types_by_name['ControlCommand'] = _CONTROLCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pause = _reflection.GeneratedProtocolMessageType('Pause', (_message.Message,), {
  'DESCRIPTOR' : _PAUSE,
  '__module__' : 'edu.uci.ics.amber.engine.architecture.worker.promisehandler2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.architecture.worker.Pause)
  })
_sym_db.RegisterMessage(Pause)

Resume = _reflection.GeneratedProtocolMessageType('Resume', (_message.Message,), {
  'DESCRIPTOR' : _RESUME,
  '__module__' : 'edu.uci.ics.amber.engine.architecture.worker.promisehandler2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.architecture.worker.Resume)
  })
_sym_db.RegisterMessage(Resume)

AddOutputPolicy = _reflection.GeneratedProtocolMessageType('AddOutputPolicy', (_message.Message,), {
  'DESCRIPTOR' : _ADDOUTPUTPOLICY,
  '__module__' : 'edu.uci.ics.amber.engine.architecture.worker.promisehandler2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.architecture.worker.AddOutputPolicy)
  })
_sym_db.RegisterMessage(AddOutputPolicy)

ControlCommand = _reflection.GeneratedProtocolMessageType('ControlCommand', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLCOMMAND,
  '__module__' : 'edu.uci.ics.amber.engine.architecture.worker.promisehandler2_pb2'
  # @@protoc_insertion_point(class_scope:edu.uci.ics.amber.engine.architecture.worker.ControlCommand)
  })
_sym_db.RegisterMessage(ControlCommand)


# @@protoc_insertion_point(module_scope)
