// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.promisehandler2

object Promisehandler2Proto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.sendsemantics.datatransferpolicy2.Datatransferpolicy2Proto,
    edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto,
    edu.uci.ics.amber.engine.common.statetransition2.Statetransition2Proto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.QueryStatistics,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.StartWorker,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.WorkerStatistics,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.UpdateInputLinking,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.AddOutputPolicy,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.WorkerExecutionCompleted,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.ControlCommandMessage
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkJlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci9wcm9taXNlaGFuZGxlcjIucHJvdG8SLGVkd
  S51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyGk1lZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0Z
  WN0dXJlL3NlbmRzZW1hbnRpY3MvZGF0YXRyYW5zZmVycG9saWN5Mi5wcm90bxo1ZWR1L3VjaS9pY3MvYW1iZXIvZW5naW5lL2Nvb
  W1vbi92aXJ0dWFsaWRlbnRpdHkucHJvdG8aNmVkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9jb21tb24vc3RhdGV0cmFuc2l0aW9uM
  i5wcm90byIRCg9RdWVyeVN0YXRpc3RpY3MiDQoLU3RhcnRXb3JrZXIi6wEKEFdvcmtlclN0YXRpc3RpY3MSYAoLd29ya2VyU3Rhd
  GUYASABKAsyLC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLldvcmtlclN0YXRlQhDiPw0SC3dvcmtlclN0YXRlUgt3b
  3JrZXJTdGF0ZRI4Cg1pbnB1dFJvd0NvdW50GAIgASgDQhLiPw8SDWlucHV0Um93Q291bnRSDWlucHV0Um93Q291bnQSOwoOb3V0c
  HV0Um93Q291bnQYAyABKANCE+I/EBIOb3V0cHV0Um93Q291bnRSDm91dHB1dFJvd0NvdW50ItkBChJVcGRhdGVJbnB1dExpbmtpb
  mcSZgoKaWRlbnRpZmllchgBIAEoCzI1LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5jb21tb24uQWN0b3JWaXJ0dWFsSWRlbnRpd
  HlCD+I/DBIKaWRlbnRpZmllclIKaWRlbnRpZmllchJbCglpbnB1dExpbmsYAiABKAsyLS5lZHUudWNpLmljcy5hbWJlci5lbmdpb
  mUuY29tbW9uLkxpbmtJZGVudGl0eUIO4j8LEglpbnB1dExpbmtSCWlucHV0TGluayJ+Cg9BZGRPdXRwdXRQb2xpY3kSawoGcG9sa
  WN5GAEgASgLMkYuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS5zZW5kc2VtYW50aWNzLkRhdGFTZW5kaW5nU
  G9saWN5QgviPwgSBnBvbGljeVIGcG9saWN5IhoKGFdvcmtlckV4ZWN1dGlvbkNvbXBsZXRlZCLNBgoOQ29udHJvbENvbW1hbmQSf
  woPYWRkT3V0cHV0UG9saWN5GAMgASgLMj0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuQWRkT
  3V0cHV0UG9saWN5QhTiPxESD2FkZE91dHB1dFBvbGljeUgAUg9hZGRPdXRwdXRQb2xpY3kSbwoLc3RhcnRXb3JrZXIYBCABKAsyO
  S5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5TdGFydFdvcmtlckIQ4j8NEgtzdGFydFdvcmtlc
  kgAUgtzdGFydFdvcmtlchKLAQoSdXBkYXRlSW5wdXRMaW5raW5nGAUgASgLMkAuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY
  2hpdGVjdHVyZS53b3JrZXIuVXBkYXRlSW5wdXRMaW5raW5nQhfiPxQSEnVwZGF0ZUlucHV0TGlua2luZ0gAUhJ1cGRhdGVJbnB1d
  ExpbmtpbmcSfwoPcXVlcnlTdGF0aXN0aWNzGAYgASgLMj0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b
  3JrZXIuUXVlcnlTdGF0aXN0aWNzQhTiPxESD3F1ZXJ5U3RhdGlzdGljc0gAUg9xdWVyeVN0YXRpc3RpY3MSgwEKEHdvcmtlclN0Y
  XRpc3RpY3MYByABKAsyPi5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5Xb3JrZXJTdGF0aXN0a
  WNzQhXiPxISEHdvcmtlclN0YXRpc3RpY3NIAFIQd29ya2VyU3RhdGlzdGljcxKjAQoYd29ya2VyRXhlY3V0aW9uQ29tcGxldGVkG
  GUgASgLMkYuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuV29ya2VyRXhlY3V0aW9uQ29tcGxld
  GVkQh3iPxoSGHdvcmtlckV4ZWN1dGlvbkNvbXBsZXRlZEgAUhh3b3JrZXJFeGVjdXRpb25Db21wbGV0ZWRCDgoMc2VhbGVkX3Zhb
  HVlYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.sendsemantics.datatransferpolicy2.Datatransferpolicy2Proto.javaDescriptor,
      edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.statetransition2.Statetransition2Proto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}