// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.promisehandler2

object Promisehandler2Proto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.sendsemantics.datatransferpolicy2.Datatransferpolicy2Proto,
    edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto,
    edu.uci.ics.amber.engine.common.statetransition2.Statetransition2Proto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.PauseWorker,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.ResumeWorker,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.StartWorker,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.QueryStatistics,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.WorkerStatistics,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.WorkerStateInfo,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.UpdateInputLinking,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.AddOutputPolicy,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.WorkerExecutionCompleted,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.SendPythonUDF,
      edu.uci.ics.amber.engine.architecture.worker.promisehandler2.ControlCommandMessage
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkJlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci9wcm9taXNlaGFuZGxlcjIucHJvdG8SLGVkd
  S51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyGk1lZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0Z
  WN0dXJlL3NlbmRzZW1hbnRpY3MvZGF0YXRyYW5zZmVycG9saWN5Mi5wcm90bxo1ZWR1L3VjaS9pY3MvYW1iZXIvZW5naW5lL2Nvb
  W1vbi92aXJ0dWFsaWRlbnRpdHkucHJvdG8aNmVkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9jb21tb24vc3RhdGV0cmFuc2l0aW9uM
  i5wcm90byINCgtQYXVzZVdvcmtlciIOCgxSZXN1bWVXb3JrZXIiDQoLU3RhcnRXb3JrZXIiEQoPUXVlcnlTdGF0aXN0aWNzIusBC
  hBXb3JrZXJTdGF0aXN0aWNzEmAKC3dvcmtlclN0YXRlGAEgASgLMiwuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvbW1vbi5Xb
  3JrZXJTdGF0ZUIQ4j8NEgt3b3JrZXJTdGF0ZVILd29ya2VyU3RhdGUSOAoNaW5wdXRSb3dDb3VudBgCIAEoA0IS4j8PEg1pbnB1d
  FJvd0NvdW50Ug1pbnB1dFJvd0NvdW50EjsKDm91dHB1dFJvd0NvdW50GAMgASgDQhPiPxASDm91dHB1dFJvd0NvdW50Ug5vdXRwd
  XRSb3dDb3VudCJzCg9Xb3JrZXJTdGF0ZUluZm8SYAoLd29ya2VyU3RhdGUYASABKAsyLC5lZHUudWNpLmljcy5hbWJlci5lbmdpb
  mUuY29tbW9uLldvcmtlclN0YXRlQhDiPw0SC3dvcmtlclN0YXRlUgt3b3JrZXJTdGF0ZSLZAQoSVXBkYXRlSW5wdXRMaW5raW5nE
  mYKCmlkZW50aWZpZXIYASABKAsyNS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yVmlydHVhbElkZW50aXR5Q
  g/iPwwSCmlkZW50aWZpZXJSCmlkZW50aWZpZXISWwoJaW5wdXRMaW5rGAIgASgLMi0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lL
  mNvbW1vbi5MaW5rSWRlbnRpdHlCDuI/CxIJaW5wdXRMaW5rUglpbnB1dExpbmsifgoPQWRkT3V0cHV0UG9saWN5EmsKBnBvbGlje
  RgBIAEoCzJGLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuc2VuZHNlbWFudGljcy5EYXRhU2VuZGluZ1Bvb
  GljeUIL4j8IEgZwb2xpY3lSBnBvbGljeSIaChhXb3JrZXJFeGVjdXRpb25Db21wbGV0ZWQiKwoNU2VuZFB5dGhvblVERhIaCgN1Z
  GYYASABKAlCCOI/BRIDdWRmUgN1ZGYirQoKDkNvbnRyb2xDb21tYW5kEm8KC3BhdXNlV29ya2VyGAEgASgLMjkuZWR1LnVjaS5pY
  3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuUGF1c2VXb3JrZXJCEOI/DRILcGF1c2VXb3JrZXJIAFILcGF1c2VXb
  3JrZXIScwoMcmVzdW1lV29ya2VyGAIgASgLMjouZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuU
  mVzdW1lV29ya2VyQhHiPw4SDHJlc3VtZVdvcmtlckgAUgxyZXN1bWVXb3JrZXISfwoPYWRkT3V0cHV0UG9saWN5GAMgASgLMj0uZ
  WR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuQWRkT3V0cHV0UG9saWN5QhTiPxESD2FkZE91dHB1d
  FBvbGljeUgAUg9hZGRPdXRwdXRQb2xpY3kSbwoLc3RhcnRXb3JrZXIYBCABKAsyOS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY
  XJjaGl0ZWN0dXJlLndvcmtlci5TdGFydFdvcmtlckIQ4j8NEgtzdGFydFdvcmtlckgAUgtzdGFydFdvcmtlchKLAQoSdXBkYXRlS
  W5wdXRMaW5raW5nGAUgASgLMkAuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuVXBkYXRlSW5wd
  XRMaW5raW5nQhfiPxQSEnVwZGF0ZUlucHV0TGlua2luZ0gAUhJ1cGRhdGVJbnB1dExpbmtpbmcSfwoPcXVlcnlTdGF0aXN0aWNzG
  AYgASgLMj0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuUXVlcnlTdGF0aXN0aWNzQhTiPxESD
  3F1ZXJ5U3RhdGlzdGljc0gAUg9xdWVyeVN0YXRpc3RpY3MSgwEKEHdvcmtlclN0YXRpc3RpY3MYByABKAsyPi5lZHUudWNpLmljc
  y5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5Xb3JrZXJTdGF0aXN0aWNzQhXiPxISEHdvcmtlclN0YXRpc3RpY3NIA
  FIQd29ya2VyU3RhdGlzdGljcxJ/Cg93b3JrZXJTdGF0ZUluZm8YCCABKAsyPS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJja
  Gl0ZWN0dXJlLndvcmtlci5Xb3JrZXJTdGF0ZUluZm9CFOI/ERIPd29ya2VyU3RhdGVJbmZvSABSD3dvcmtlclN0YXRlSW5mbxJ3C
  g1zZW5kUHl0aG9uVURGGAkgASgLMjsuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuU2VuZFB5d
  GhvblVERkIS4j8PEg1zZW5kUHl0aG9uVURGSABSDXNlbmRQeXRob25VREYSowEKGHdvcmtlckV4ZWN1dGlvbkNvbXBsZXRlZBhlI
  AEoCzJGLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLldvcmtlckV4ZWN1dGlvbkNvbXBsZXRlZ
  EId4j8aEhh3b3JrZXJFeGVjdXRpb25Db21wbGV0ZWRIAFIYd29ya2VyRXhlY3V0aW9uQ29tcGxldGVkQg4KDHNlYWxlZF92YWx1Z
  WIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.sendsemantics.datatransferpolicy2.Datatransferpolicy2Proto.javaDescriptor,
      edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.statetransition2.Statetransition2Proto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}
